@@
-mixpanel-android = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanel-android" }
+# mixpanel removed to disable analytics
@@
-    mixpanel-android = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanel-android" }
+    # mixpanel removed to disable analytics
